/**
 * Root layout.
 *
 * Runs the launch-time session restore and holds the splash screen until it
 * settles, so the user never sees a flash of login before being routed to their
 * dashboard.
 *
 * Heavy native modules (SQLite, NetInfo) are loaded lazily rather than at module
 * scope — in Expo Go some of them are unavailable, and importing them eagerly here
 * took the whole app down before the first render.
 */

import { useEffect } from 'react';
import { AppState, LogBox, type AppStateStatus } from 'react-native';
import { Stack } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import * as SplashScreen from 'expo-splash-screen';
import * as SystemUI from 'expo-system-ui';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { focusManager, QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { colors, motion } from '@/constants/theme';
import { useAuthStore } from '@/stores/authStore';

void SplashScreen.preventAutoHideAsync();

/**
 * Paints the native root view the app background.
 *
 * This is the surface *behind* the React tree, and it was the black box flashing during
 * navigation. Nothing in JS was at fault: every screen container is already opaque
 * (`Screen`, the Stack's `contentStyle`, the Tabs' `sceneStyle`). But a cross-fade puts
 * the outgoing and incoming scene below full opacity at the same moment, and opacity
 * applies to a view's own background too — so for a few frames the window showed through
 * whatever both scenes no longer covered.
 *
 * That window had no colour of its own. `AppTheme` inherits
 * `Theme.AppCompat.DayNight.NoActionBar`, which resolves to near-black on a device in
 * dark mode, and Expo only writes an explicit `android:windowBackground` when the app
 * config declares a background colour.
 *
 * `backgroundColor` in app.json is the real fix and covers the very first frame, before
 * any JS runs. This call is the same value applied at runtime, so the fix also holds in
 * an existing native project that has not been regenerated by `expo prebuild`.
 */
// Swallowing the rejection rather than letting it surface: this runs at module scope to
// land before the first frame, and a purely cosmetic backdrop is not worth an unhandled
// rejection if the native module is not ready yet. app.json still covers the same case.
SystemUI.setBackgroundColorAsync(colors.background).catch(() => {});

/**
 * Silences one deprecation notice raised by dependencies, not by this app.
 *
 * React Native 0.86 deprecated `InteractionManager`. Two installed packages still call it,
 * and neither call site is ours:
 *
 *   - `expo-router`, in its vendored copy of the React Navigation stack card, on every
 *     screen transition. Still present in 57.0.18, the newest build for SDK 57.
 *   - `react-native-draggable-flatlist`, when a reordered list's data changes.
 *
 * It fires on more or less every navigation, which buries the warnings that *are* worth
 * reading. Matched on the exact opening phrase rather than a broad pattern, so it hides
 * this notice and nothing else, and only in development — LogBox does not run in release
 * builds.
 *
 * Remove this once both packages drop the call. Nothing in the app depends on it, so
 * deleting it is always safe: the worst case is the noise returns.
 */
if (__DEV__) {
  LogBox.ignoreLogs(['InteractionManager has been deprecated']);
}

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Data refreshes automatically when a screen mounts or the user pulls to refresh.
      staleTime: 0,
      refetchOnMount: 'always',

      // Keep unmounted query data in memory for 10 minutes so returning to a
      // previously visited screen shows cached data while refetching.
      gcTime: 10 * 60 * 1000, // 10 minutes

      // 4xx will not succeed on a retry; only retry transport failures.
      retry: (failureCount, error: unknown) => {
        const status = (error as { status?: number } | null)?.status ?? 0;
        if (status >= 400 && status < 500) return false;
        return failureCount < 2;
      },
    },
    mutations: {
      // No blind retries on writes. Submitting answers upserts on
      // (student, date) so a repeat is harmless, but a review decision is
      // rejected once already decided — retrying it would surface a confusing
      // "already reviewed" error instead of the original failure.
      retry: false,
    },
  },
});

export default function RootLayout() {
  const bootstrap = useAuthStore((state) => state.bootstrap);
  const isBootstrapping = useAuthStore((state) => state.isBootstrapping);

  useEffect(() => {
    // Never leave the user on a blank splash screen if the session check stalls.
    const timeout = setTimeout(() => {
      if (useAuthStore.getState().isBootstrapping) {
        useAuthStore.setState({ isBootstrapping: false, isAuthenticated: false, user: null });
      }
    }, 6000);

    void bootstrap().finally(() => clearTimeout(timeout));

    return () => clearTimeout(timeout);
  }, [bootstrap]);

  useEffect(() => {
    if (isBootstrapping) return;
    void SplashScreen.hideAsync();
  }, [isBootstrapping]);

  /**
   * React Query's focus tracking is written for the web, where it listens for
   * window focus events that never fire in React Native. Feeding it AppState is
   * what makes two things work: polling queries pause while the app is
   * backgrounded instead of burning battery, and everything refetches the moment
   * the user comes back, so a screen never shows numbers from ten minutes ago.
   *
   * The same transition re-reads the identity. `bootstrap` falls back to a provisional
   * identity when `/auth/me` cannot be reached, and that fallback deliberately assumes the
   * least privilege it can rather than trusting a role the account holder could have
   * written. Without a retry the guess would stick for the whole session — a faculty member
   * who launched with no signal would sit in the student area until they killed the app,
   * because `refreshUser` existed but nothing ever called it. Coming back to the
   * foreground is the natural moment to ask again.
   */
  useEffect(() => {
    focusManager.setFocused(AppState.currentState === 'active');

    const subscription = AppState.addEventListener('change', (status: AppStateStatus) => {
      const active = status === 'active';
      focusManager.setFocused(active);
      // No-ops when signed out, and keeps `status` and `role` current for a session that
      // was suspended or re-scoped while the app sat in the background.
      if (active) void useAuthStore.getState().refreshUser();
    });

    return () => subscription.remove();
  }, []);

  // Splash screen is still up; rendering a tree here would only be redirected away.
  if (isBootstrapping) return null;

  return (
    <SafeAreaProvider>
      <QueryClientProvider client={queryClient}>
        <StatusBar style="light" />
        {/*
          Every screen here is a whole role area, reached by replacing the stack rather
          than pushing onto it — logging in, logging out, being redirected by role. So they
          cross-fade instead of sliding: a slide implies "forward, and back again", which is
          not what any of these transitions are.

          `contentStyle` carries the app background so the fade happens between two
          coloured screens. Without it the transition passes through the default white,
          which is the flash that makes a switch feel like a jolt rather than a movement.
        */}
        <Stack
          screenOptions={{
            headerStyle: { backgroundColor: colors.primary },
            headerTintColor: colors.onPrimary,
            headerTitleStyle: { fontWeight: '600' },
            contentStyle: { backgroundColor: colors.background },
            headerShown: false,
            animation: 'fade',
            animationDuration: motion.fade,
          }}
        >
          <Stack.Screen name="index" />
          <Stack.Screen name="(auth)" />
          <Stack.Screen name="(student)" />
          <Stack.Screen name="(faculty)" />
          <Stack.Screen name="(admin)" />
        </Stack>
      </QueryClientProvider>
    </SafeAreaProvider>
  );
}
